/**
 * Capture Task and Result Types
 */

import type { BrowserOptions } from "../config/index.js";
import type { WorkerStatus } from "./worker-status.js";
import type { CaptureOptions } from "./capture-mode.js";
import type { CaptureStatus } from "./capture-status.js";

export type ValidationResult =
  | { valid: true }
  | { valid: false; error: string };

/** Capture task representing a single URL to capture */
export interface CaptureTask {
  /** Task ID generated by the server (UUID v4) */
  taskId: string;
  /** Correlation ID provided by the client (optional) */
  correlationId?: string;
  /** Display labels (used for filename) */
  labels: string[];
  url: string;
  retryCount: number;
  captureOptions: CaptureOptions;
}

export interface CaptureResult {
  /** The task that was processed */
  task: CaptureTask;
  /** Result status */
  status: CaptureStatus;
  /** HTTP response status code (e.g., 200, 403, 404, 500) */
  httpStatusCode?: number;
  pngPath?: string;
  jpegPath?: string;
  htmlPath?: string;
  error?: string;
  captureProcessingTimeMs: number;
  timestamp: string;
  workerId: string;
}

export interface ErrorTaskInfo {
  taskId: string;
  url: string;
  labels: string[];
}

export interface ErrorRecord {
  message: string;
  /** Timestamp when error occurred (ISO 8601 format) */
  timestamp: string;
  /** Task information (optional, not set for non-task errors like connection failures) */
  task?: ErrorTaskInfo;
}

export interface WorkerInfo {
  id: string;
  browserOptions: BrowserOptions;
  status: WorkerStatus;
  processedCount: number;
  errorCount: number;
  /** Error history (up to 10 most recent errors, newest first) */
  errorHistory: ErrorRecord[];
}

