/**
 * Capture Task and Result Types
 */

import type { BrowserProfile } from "../config/index.js";
import type { WorkerHealth } from "./capture-worker.js";
import type { CaptureFormats } from "./capture-formats.js";
import type { CaptureStatus } from "./capture-status.js";
import type { ErrorType } from "./error-type.js";
import type { DismissOptions, DismissReport } from "./banner-dismisser.js";

/** Capture task representing a single URL to capture */
export interface CaptureTask {
  /** Task ID generated by the server (UUID v4) */
  taskId: string;
  /** Correlation ID provided by the client (optional) */
  correlationId?: string;
  /** Display labels (used for filename) */
  labels: string[];
  url: string;
  retryCount: number;
  captureFormats: CaptureFormats;
  /**
   * Upstream `Accept-Language` header to send for this capture. Validated
   * by the OpenAPI schema (printable ASCII only, ≤ 200 chars). Undefined
   * means "let Chromium use its built-in default".
   */
  acceptLanguage?: string;
  /**
   * Resolved banner / modal dismissal options. Presence indicates the
   * dismissal pass should run with these options; absence means skip.
   * The HTTP layer's `dismissBanners` field (boolean | DismissSpec) is
   * normalized into this shape by `resolveDismissSpec` at the
   * `request-mapper` boundary, so the capture layer only ever sees a
   * fully-resolved `DismissOptions` (or `undefined` for "no dismissal").
   */
  dismissOptions?: DismissOptions;
  /**
   * ISO 8601 wall-clock time of the original enqueue. Preserved across
   * retries (`TaskQueue.requeue`) so a long-stuck task's true age stays
   * visible in `/v1/status`.
   */
  enqueuedAt: string;
}

export interface ErrorDetails {
  type: ErrorType;
  message: string;
  httpStatusCode?: number;
  httpStatusText?: string;
  timeoutMs?: number;
}

export interface CaptureResult {
  /** The task that was processed */
  task: CaptureTask;
  /** Result status */
  status: CaptureStatus;
  /** HTTP response status code (e.g., 200, 403, 404, 500) */
  httpStatusCode?: number;
  pngPath?: string;
  jpegPath?: string;
  htmlPath?: string;
  /** Path to the extracted links JSON (only set when `task.captureFormats.links` is true) */
  linksPath?: string;
  errorDetails?: ErrorDetails;
  captureProcessingTimeMs: number;
  timestamp: string;
  workerIndex: number;
  /** Banner dismissal report (only set when `task.dismissBanners` is true) */
  dismissReport?: DismissReport;
}

/** A single anchor link extracted from a captured page. */
export interface LinkRecord {
  /** Absolute URL (already resolved against the page's base URL by the browser). */
  href: string;
  /** Trimmed `textContent`, capped at 200 chars. */
  text: string;
  /** Raw `rel` attribute (e.g. `"nofollow"`, `"nofollow noreferrer"`), or null when absent. */
  rel: string | null;
}

/** Shape of the JSON file written when `task.captureFormats.links` is true. */
export interface LinksFile {
  taskId: string;
  /** The URL the task asked to capture (pre-redirect). */
  url: string;
  /** The URL Chromium ended up on after any redirects (`page.url()`). */
  finalUrl: string;
  labels: string[];
  correlationId?: string;
  /** ISO 8601 timestamp of when the link extraction completed. */
  capturedAt: string;
  links: LinkRecord[];
}

export interface ErrorTaskInfo {
  taskId: string;
  url: string;
  labels: string[];
}

export interface ErrorRecord extends ErrorDetails {
  /** Timestamp when error occurred (ISO 8601 format) */
  timestamp: string;
  /** Task information (optional, not set for non-task errors like connection failures) */
  task?: ErrorTaskInfo;
}

/**
 * Snapshot of the task a worker is currently processing.
 *
 * `startedAt` is an ISO 8601 string (the in-context epoch ms is converted
 * at the domain boundary by `CaptureWorker.toInfo`). `elapsedMs` is not
 * stored — the wire layer computes it from `startedAt` at response build
 * time so the value reflects the actual response moment.
 */
export interface CurrentTaskInfo {
  task: CaptureTask;
  startedAt: string;
}

export interface WorkerInfo {
  index: number;
  browserProfile: BrowserProfile;
  health: WorkerHealth;
  processedCount: number;
  errorCount: number;
  /** Error history (up to 10 most recent errors, newest first) */
  errorHistory: ErrorRecord[];
  /** Set only while the worker is busy processing a task */
  currentTask?: CurrentTaskInfo;
}

