/**
 * Capture Task and Result Types
 */

import type { BrowserProfile } from "../config/index.js";
import type { WorkerHealth } from "./capture-worker.js";
import type { CaptureFormats } from "./capture-formats.js";
import type { CaptureStatus } from "./capture-status.js";
import type { ErrorType } from "./error-type.js";
import type { DismissReport } from "./banner-dismisser.js";

/** Capture task representing a single URL to capture */
export interface CaptureTask {
  /** Task ID generated by the server (UUID v4) */
  taskId: string;
  /** Correlation ID provided by the client (optional) */
  correlationId?: string;
  /** Display labels (used for filename) */
  labels: string[];
  url: string;
  retryCount: number;
  captureFormats: CaptureFormats;
  /** Whether to run banner / modal dismissal before capturing */
  dismissBanners: boolean;
}

export interface ErrorDetails {
  type: ErrorType;
  message: string;
  httpStatusCode?: number;
  httpStatusText?: string;
  timeoutMs?: number;
}

export interface CaptureResult {
  /** The task that was processed */
  task: CaptureTask;
  /** Result status */
  status: CaptureStatus;
  /** HTTP response status code (e.g., 200, 403, 404, 500) */
  httpStatusCode?: number;
  pngPath?: string;
  jpegPath?: string;
  htmlPath?: string;
  errorDetails?: ErrorDetails;
  captureProcessingTimeMs: number;
  timestamp: string;
  workerIndex: number;
  /** Banner dismissal report (only set when `task.dismissBanners` is true) */
  dismissReport?: DismissReport;
}

export interface ErrorTaskInfo {
  taskId: string;
  url: string;
  labels: string[];
}

export interface ErrorRecord extends ErrorDetails {
  /** Timestamp when error occurred (ISO 8601 format) */
  timestamp: string;
  /** Task information (optional, not set for non-task errors like connection failures) */
  task?: ErrorTaskInfo;
}

export interface WorkerInfo {
  index: number;
  browserProfile: BrowserProfile;
  health: WorkerHealth;
  processedCount: number;
  errorCount: number;
  /** Error history (up to 10 most recent errors, newest first) */
  errorHistory: ErrorRecord[];
}

