import { defineConfig } from "@hey-api/openapi-ts";

/**
 * Single source of truth: src/http/openapi.yaml.
 *
 * Generates types, an operationId-keyed SDK (e.g. `submitCapture(...)`),
 * and a fetch-based client into src/http/generated/. The default client
 * baseUrl is auto-extracted from `servers[0].url` in the spec.
 *
 * Output is gitignored (see .gitignore: src/http/generated/) and
 * regenerated by the prebuild / pretest / prelint hooks.
 */
export default defineConfig({
  input: "src/http/openapi.yaml",
  output: "src/http/generated",
  plugins: ["@hey-api/client-fetch"],
});
