/**
 * Sample client that submits capture requests from a YAML data file (fire-and-forget).
 *
 * Calls the operationId-keyed SDK functions generated by
 * @hey-api/openapi-ts from src/http/openapi.yaml. Path / method /
 * request / response shapes are all driven from the spec — no
 * hardcoded URL strings here.
 *
 * The data-file format and parser live in `examples/data-file.ts` so they
 * can be unit-tested independently of this script's `main()` IIFE.
 *
 * ## Capture format flags
 *
 * `--png` / `--webp` / `--html` / `--links` / `--mhtml` /
 * `--wacz` のうち少なくとも 1 つを指定する必要がある（サーバ側で
 * `validateCaptureFormats` がチェック）。
 *
 * ## --mhtml
 *
 * CDP `Page.captureSnapshot` で `.mhtml` (multipart archive) を S3 に保存
 * する — 関連リソースを単一ファイルに同梱するためオフラインでも見た目が
 * 再現される。
 *
 * ## --wacz
 *
 * キャプチャ中の全 HTTP セッション (将来のスクロール起因の遅延ロード
 * リソースを含む) を WACZ アーカイブとして保存し、ReplayWeb.page
 * (https://replayweb.page/) で対話的にリプレイできる — 詳しくは
 * https://uraitakahito.github.io/browserhive/replay-quickstart/ を参照。
 *
 * ## data/accept-language.yaml
 *
 * Hand-curated subset of `data/nikkei225.yaml` whose top pages serve
 * different content (or redirect to a different URL) for `ja` vs `en`.
 * Useful as a regression / demo fixture for the `--accept-language` flag.
 */
import { readFile } from "node:fs/promises";
import {
  parseClientOptions,
  logClientConfig,
  getCaptureFormats,
  type ClientOptions,
} from "../src/cli/client-cli.js";
import { client } from "../src/http/generated/client.gen.js";
import {
  submitCapture,
  type CaptureRequest,
} from "../src/http/generated/index.js";
import type { CaptureFormats } from "../src/capture/index.js";
import type { ArchiveMode } from "../src/config/index.js";
import { logger } from "../src/logger.js";
import { parseDataFile, type DataEntry } from "./data-file.js";
import {
  loadBehaviorRegistry,
  selectForHost,
  type CustomBehavior,
} from "./behaviors-loader.js";

interface SubmitResult {
  taskId: string;
  correlationId: string;
  labels: string[];
  accepted: boolean;
  /** Ids of the custom behaviors attached to this request (by host match). */
  behaviors: string[];
  error?: string;
}

const generateRandomId = (length: number): string => {
  const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let result = "";
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};

/**
 * For TLS server verification with a custom CA, set the
 * `NODE_EXTRA_CA_CERTS` env var to the CA certificate path before
 * starting the process. The `--tls-ca-cert` flag is logged for
 * visibility but is otherwise informational — Node's global fetch picks
 * up the trust anchor from the env var and the hey-api fetch client
 * delegates to global fetch.
 */
const configureClient = (options: ClientOptions): void => {
  if (options.server !== undefined) {
    client.setConfig({ baseUrl: options.server });
  }
};

const submitRequest = async (
  entry: DataEntry,
  captureFormats: CaptureFormats,
  dismissBanners: boolean,
  acceptLanguage: string | undefined,
  viewport: { width: number; height: number } | undefined,
  deviceScaleFactor: number | undefined,
  operationDelayMs: number | undefined,
  archiveMode: ArchiveMode | undefined,
  fullPage: boolean | undefined,
  signing: boolean,
  cache: CaptureRequest["cache"],
  selectBehaviors: (host: string) => CustomBehavior[],
): Promise<SubmitResult> => {
  const correlationId = generateRandomId(5);
  // Attach custom behaviors matched by the target host. Only `custom` is sent:
  // sending `builtins` would replace the server's enabled built-in set for this
  // capture, so the built-ins are left to the server's own configuration.
  const custom = selectBehaviors(new URL(entry.url).hostname);
  const behaviors = custom.map((c) => c.id);
  const body: CaptureRequest = {
    url: entry.url,
    labels: entry.labels,
    correlationId,
    captureFormats,
    dismissBanners,
    ...(acceptLanguage !== undefined && { acceptLanguage }),
    ...(viewport !== undefined && { viewport }),
    ...(deviceScaleFactor !== undefined && { deviceScaleFactor }),
    ...(operationDelayMs !== undefined && { operationDelayMs }),
    ...(archiveMode !== undefined && { archiveMode }),
    ...(fullPage !== undefined && { fullPage }),
    // Only meaningful with captureFormats.wacz — the server rejects the other
    // combination rather than accepting a request it cannot satisfy. A capture
    // whose signature fails still succeeds; check `signature.signed` on the
    // result to tell a signed archive from an unsigned one.
    ...(signing && { signing: true }),
    // Omitted → the server default, which ships as `clear`: a repeat capture
    // of the same URL would otherwise revalidate and come back as a bodyless
    // 304, failing the capture.
    ...(cache === undefined ? {} : { cache }),
    ...(custom.length > 0 && { behaviors: { custom } }),
  };

  try {
    const { data, error, response } = await submitCapture({ body });
    if (response?.status === 202 && data) {
      return {
        taskId: data.taskId,
        correlationId,
        labels: entry.labels,
        accepted: true,
        behaviors,
      };
    }
    const status = response?.status;
    const message =
      error?.detail ?? error?.title ?? (status !== undefined ? `HTTP ${String(status)}` : "Network error");
    return {
      taskId: "",
      correlationId,
      labels: entry.labels,
      accepted: false,
      behaviors,
      error: message,
    };
  } catch (caught) {
    const errorMessage = caught instanceof Error ? caught.message : String(caught);
    return {
      taskId: "",
      correlationId,
      labels: entry.labels,
      accepted: false,
      behaviors,
      error: errorMessage,
    };
  }
};

const submitAll = async (
  entries: DataEntry[],
  captureFormats: CaptureFormats,
  dismissBanners: boolean,
  acceptLanguage: string | undefined,
  viewport: { width: number; height: number } | undefined,
  deviceScaleFactor: number | undefined,
  operationDelayMs: number | undefined,
  archiveMode: ArchiveMode | undefined,
  fullPage: boolean | undefined,
  signing: boolean,
  cache: CaptureRequest["cache"],
  selectBehaviors: (host: string) => CustomBehavior[],
): Promise<SubmitResult[]> => {
  const total = entries.length;
  let completed = 0;

  const promises = entries.map(async (entry) => {
    const result = await submitRequest(
      entry,
      captureFormats,
      dismissBanners,
      acceptLanguage,
      viewport,
      deviceScaleFactor,
      operationDelayMs,
      archiveMode,
      fullPage,
      signing,
      cache,
      selectBehaviors,
    );
    completed++;

    if (result.accepted) {
      logger.info(
        { progress: `${String(completed)}/${String(total)}`, taskId: result.taskId, correlationId: result.correlationId, labels: result.labels, behaviors: result.behaviors },
        "Request accepted",
      );
    } else {
      logger.warn(
        { progress: `${String(completed)}/${String(total)}`, taskId: result.taskId, correlationId: result.correlationId, labels: result.labels, error: result.error ?? "Unknown error" },
        "Request rejected",
      );
    }

    return result;
  });

  return Promise.all(promises);
};

const logSummary = (results: SubmitResult[], totalDuration: number): void => {
  const acceptedCount = results.filter((r) => r.accepted).length;
  const rejectedCount = results.filter((r) => !r.accepted).length;

  logger.info(
    {
      total: results.length,
      accepted: acceptedCount,
      rejected: rejectedCount,
      durationMs: totalDuration,
    },
    "Request summary",
  );
};

const runClient = async (options: ClientOptions): Promise<void> => {
  const startTime = Date.now();

  logClientConfig(options);
  configureClient(options);

  const fileContent = await readFile(options.data, "utf-8");
  const parseResult = parseDataFile(fileContent);
  if (!parseResult.ok) {
    logger.fatal({ file: options.data, error: parseResult.error }, "Failed to parse data file");
    process.exit(1);
  }
  let entries = parseResult.value;
  const totalInFile = entries.length;

  if (options.limit !== undefined && options.limit > 0) {
    entries = entries.slice(0, options.limit);
  }

  logger.info({ count: entries.length, total: totalInFile }, "Loaded entries from data file");

  if (entries.length === 0) {
    logger.info("No entries to process");
    return;
  }

  const captureFormats = getCaptureFormats(options);
  const viewport =
    options.viewportWidth !== undefined && options.viewportHeight !== undefined
      ? { width: options.viewportWidth, height: options.viewportHeight }
      : undefined;
  // Build the custom-behavior registry once, then attach per-entry by host.
  const registry = loadBehaviorRegistry(options.behaviorsVersion ?? "v1.0");
  const results = await submitAll(
    entries,
    captureFormats,
    options.dismissBanners ?? false,
    options.acceptLanguage,
    viewport,
    options.deviceScaleFactor,
    options.operationDelayMs,
    options.archiveMode,
    options.fullPage,
    options.signing ?? false,
    options.cache,
    (host) => selectForHost(registry, host),
  );

  const totalDuration = Date.now() - startTime;
  logSummary(results, totalDuration);
};

const main = async (): Promise<void> => {
  const options = parseClientOptions(process.argv);
  await runClient(options);
};

main().catch((error: unknown) => {
  logger.fatal({ err: error }, "Fatal error");
  process.exit(1);
});
