#!/usr/bin/env node
/**
 * Generate src/generated/version.ts with the build fingerprint the server
 * exposes at /v1/status.build: { version, revision, buildTime }.
 *
 * Runs at build time (via the `prep` step, before tsc / tests / lint), so the
 * values are baked into the compiled output and never read at runtime.
 *
 * revision resolution:
 *   1. process.env.GIT_REV  — how Docker passes it (the build context has no
 *      .git, so `git rev-parse` cannot work inside the image build).
 *   2. `git rev-parse --short HEAD` — host / local builds.
 *   3. "dev" — neither available.
 *
 * version resolution: GIT_TAG, then `git describe --tags`, then the literal
 * "unknown". Not package.json — nothing in this workspace keeps that field in
 * step with releases (it has said 1.0.0 since the day it was written, through
 * every tag), so a build falling back to it reports a number that matches no
 * release anyone can fetch. The tag is what a release IS here.
 *
 * Falling back to package.json is how `browserhive/1.0.0` ended up stamped
 * into every archive ever produced: this value also becomes the `software`
 * field of `datapackage.json` and the WARC `warcinfo` record, where it is
 * baked in and cannot be corrected afterwards. "unknown" is worse to look at
 * and better to receive — an archive that admits it does not know beats one
 * that names a release that never existed.
 *
 * The leading `v` is dropped: `v1.9.10` is the tag name and `1.9.10` is the
 * version, and this field is the version.
 */
import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";

const git = (cmd) => {
  try {
    return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return null;
  }
};

const revision = process.env.GIT_REV?.trim() || git("git rev-parse --short HEAD") || "dev";

// `describe` also covers the off-a-release case: 1.9.10-3-gabc1234 says, out
// loud, that this build is three commits past the tag it names.
const described = process.env.GIT_TAG?.trim() || git("git describe --tags") || null;
const version = described ? described.replace(/^v/, "") : "unknown";

const info = {
  version,
  revision,
  buildTime: new Date().toISOString(),
};

mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/version.ts",
  `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit.\n` +
    `export const BUILD_INFO = ${JSON.stringify(info, null, 2)} as const;\n`,
);

console.log("generated src/generated/version.ts", info);
