#!/usr/bin/env node
/**
 * Generate src/generated/version.ts with the build fingerprint the server
 * exposes at /v1/status.build: { version, revision, buildTime }.
 *
 * Runs at build time (via the `prep` step, before tsc / tests / lint), so the
 * values are baked into the compiled output and never read at runtime.
 *
 * revision resolution:
 *   1. process.env.GIT_REV  — how Docker passes it (the build context has no
 *      .git, so `git rev-parse` cannot work inside the image build).
 *   2. `git rev-parse --short HEAD` — host / local builds.
 *   3. "dev" — neither available.
 */
import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync, readFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync("package.json", "utf8"));

const gitRev = () => {
  try {
    return execSync("git rev-parse --short HEAD", {
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
  } catch {
    return null;
  }
};

const revision = process.env.GIT_REV?.trim() || gitRev() || "dev";

const info = {
  version: pkg.version,
  revision,
  buildTime: new Date().toISOString(),
};

mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/version.ts",
  `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit.\n` +
    `export const BUILD_INFO = ${JSON.stringify(info, null, 2)} as const;\n`,
);

console.log("generated src/generated/version.ts", info);
